resolver: lts-8.22
packages:
- '.'
extra-deps:
 - hmatrix-0.18.1.0
flags: {}
extra-package-dbs: []
extra-include-dirs: []
extra-lib-dirs:
 - /nix/store/0c9wnr11z1x5js1qpm5yrirdm82fxyd6-gfortran-5.4.0-lib/lib/
nix:
  enable: true
  packages:
  - blas
  - liblapack
  - gfortran
  - ncurses